### ISSUE TITLE
Build getting denied on Google play store because of OneSignal, app made for kids

### ISSUE THREAD

**Issue by StijnAppec** [OneSignal/OneSignal-Android-SDK#1311]
**Description:**
We have an app that is made for kids. It seems like Google has recently been more active in enforcing their policies. We received an e-mail first that our submitted update was declined. We reached out to the support and got confirmation that it is indeed caused by OneSignal. 
Is there any way to make our build comply with Google's policies, and keep using OneSignal? We have implemented all our push notifications through OneSignal, and it would be a hassle to start using another solution. We do not use OneSignal for any advertising purposes.

Email received:
![alt text](https://i.imgur.com/NmEKv8Y.png)

**Environment**
Latest version (4.3.0)

**Comment by royberris** [comment]
@jkasten2 I see you're a big contributer on this repository. Can you have a look at this issue. We are also facing the same issue, where some apps are being rejected because of a advertisement identifier that is not even used by our app.

**Comment by jmadler** [comment]
Hey folks,

We believe this is caused by a static analysis tool of some kind catching the presence of the advertisingid symbol in our SDK. We had used this to detected reinstalls. We've adjusted our approach as of Android SDK 4.3.1, and that SDK version should no longer trigger a flag on their end.

Please reopen if the issue remains on SDK 4.3.1 or later.

**Comment by jasperrietrae** [comment]
Hello @jmadler, our app has been rejected again using OneSignal SDK 4.3.1. We are also contacting Google regarding the matter but I'm afraid it's still a problem on OneSignal's side.

**Comment by jmadler** [comment]
Thanks for sharing.  I've reached out to Google for help.  Feel free to email me directly if it's helpful: jordan@onesignal.com

**Comment by jkasten2** [comment]
@StijnAppec @royberris @jasperrietrae We just released [OneSignal-Android-SDK 4.3.4](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.3.4) where we completely removed all Google Ad Id references from this repo and dropped the dependency on `play-services-ads-identifier`.

If Google's detection is just a static analysis on API access / dependencies on the Ads API they run on every submission then this should solve it.
Otherwise Google may have flagged the OneSignal SDK as not compliant and we need to have Google re-evaluate our SDK which we are in the process of trying to verify.

**Comment by jasperrietrae** [comment]
@jkasten2 the app is in Review for 5 days already now.. normally this takes less than a day. Still on hold! 
![image](https://user-images.githubusercontent.com/875209/117828365-07b12d80-b272-11eb-951e-c64a4cfd6331.png)

**Comment by ArnauKokoro** [comment]
@jasperrietrae @jmadler Hi guys, do we have news about this? We would like to add new sdk version also?

Thanks!!

**Comment by ToyboxZach** [comment]
This is still happening as of our last update, curious if there is any movement from onesignal's end?

**Comment by jmadler** [comment]
We've been in ongoing conversations with Google's Business Development and Policy teams and are working to move this forward.  I wish I could provide a better update, but at this time I'm afraid we're waiting for their action.

**Comment by jasperrietrae** [comment]
We keep on getting rejected by Google and our appeals keep on getting rejected. It's been 4+ months now... we really don't want to get rid of OneSignal, but it feels like we are left to no other options at this point. Anyone with any suggestions?

**Comment by jasperrietrae** [comment]
@jmadler did you guys ever hear back anything from Google regarding this?
