### ISSUE TITLE
[Bug]:  some of the user device is not in the subscription list

### ISSUE THREAD

**Issue by softsan** [OneSignal/OneSignal-Android-SDK#2041]
### What happened?

I am using OneSignal latest SDK in my Android app. We had several beta users earlier in our app. Now we did a full roll out to production. So push notifications for those few beta users are not working and there are no subscription records of those device/users in OneSignal dashboard. It works fine for other thousand of users. but not for these few users. We already asked them to clear their cache, uninstall app and freshly install the app. We double checked that they have given push permission properly. 

So what could be the cause of this? Since this happens in Prod I don't have user device's OneSignal logs. 

Here is some code for init, setting up external id and push permission:

Initialization of OneSignal

`OneSignal.initWithContext(applicationContext, oneSignalAppId)`

set external id:
`OneSignal.login(userIdx)`

This is how i ask permission:
```
CoroutineScope(Dispatchers.IO).launch {
                OneSignal.Notifications.requestPermission(true)
            }

```
Also enabled Push permission prompt for that user and he  always received that and he always click on Allowed button.  He tried on another device and its work fine there but not working on his regular android device. Most of them have a Samsung Galaxy Android 14 devices.

Can any one help on this? 

### Steps to reproduce?

```Markdown
Device is not subscribe into onesignal
```

### What did you expect to happen?

It should subscribe and should receive push notification 

### OneSignal Android SDK version

5.1.7

### Android version

13

### Specific Android models

```Markdown
Samsung Galaxy s23
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@softsan is the user not shown at all on the OneSignal dashboard if you search by your external id? Or is it there but just not shown as subscribed?

Is everything working as expected with Android 12 and older devices?

You are not able to reproduce the issue on your test devices at all? Development or production builds?

Could you users have blocked onesignal.com? They can attempt to visit https://onesignal.com to ensure something on their device isn't blocking a connection to it.

**Comment by softsan** [comment]
@jkasten2 Thanks for quick reply. His subscription / External id is shown in OneSignal dashboard for web subscription, but not for Android subscription. 

Is everything working as expected with Android 12 and older devices?
_-- He tried on another device which was with Android 14 as well and its work there. for android 12 and older it works for other users._

You are not able to reproduce the issue on your test devices at all? Development or production builds?
_-- Yes I am not able to reproduce in my development or prod build for my user._

Could you users have blocked onesignal.com? They can attempt to visit https://onesignal.com/ to ensure something on their device isn't blocking a connection to it.
_-- No i don't think so.  we shared this link with him to see if anything missing and he confirms all works well. https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown_

Also previously we had android mobile app developed in Xamarin and now we completely write in android kotlin so that user was getting the push notification fine with the older app. but since now this new native android app is out in production, we unpublished the legacy one. 

So this user was part of legacy app and then he enrolled for our beta testing and now our official prod app in Google play he is not getting any notifications. 

We also had several other beta users but for them all works fine.

**Comment by jkasten2** [comment]
Thanks for the confirming all that and providing those extra details!

Do you happen to show the OneSignal Id or the Subscription Id in your app so end-users can see if they are subscribed?
* The idea here is to rule out the device is not creating user or subscribing at all, or just not assigning the external id.

A logcat or steps to reproduce is what would really help find the root issue here. I know this would be difficult to come by, so we will also keep an eye out if we notice such an issue in our testing.

**Comment by softsan** [comment]
Do you happen to show the OneSignal Id or the Subscription Id in your app so end-users can see if they are subscribed?

-- i am logging those details with my backend logs. So one thing i found that OneSignalId is blank for this user in my logs. For other users , it's always there.

However i see ExternalUserId in my log.

**Comment by jkasten2** [comment]
Thanks for all the details, I have undercovered some cases we are not handling login correctly and we will improve on this in the next release. I'll follow up here once it is released, then we can ask you to confirm if this gets fixed after that.

**Comment by softsan** [comment]
okay thanks. Is there any work around or solution for the time being? as our user is highly dependent on the push notification and it causes them to block from using some of my app functionality.

**Comment by jkasten2** [comment]
@softsan do you call anything other OneSignal methods before `OneSignal.login` or `OneSignal.logout`?
* We are trying to confirm if the issue we have identified also applies to this issue.

**Comment by jkasten2** [comment]
@softsan we released [5.1.8](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.8) which contains a fix that might be related to your issue. The symptoms match but the triggering seems different, as normally it was triggered by calling `addTags` followed by `login`. `addTag` is the most common User update, however any User update could trigger the issue, which was addressed in that update.

Could you try the latest version and let us know if the fixes this problem? If not could you let us know the percentage of users that seem affected by this bug?

**Comment by softsan** [comment]
@jkasten2 Sure thanks for the updates, i will try and see how it goes. in my build.gradle, i have the oneSignal like this:
`implementation 'com.onesignal:OneSignal:[5.0.0, 5.99.99]'`
So guess, it will take the 5.1.8 version as well correct? or do i explicitly define this particular version?

 We used `login` first and then use `addTags` in our android app.

**Comment by jkasten2** [comment]
The version range will include all 5.x.x versions, however it doesn't guarantee you will get that version, due to caching. To ensure you have the version I recommend bumping the minimum version:
`implementation 'com.onesignal:OneSignal:[5.1.9, 5.99.99]'`

**Comment by jkasten2** [comment]
@softsan Good to hear it sounds like things are working for you now!

> So the fix is in 5.1.9 or 5.1.8?

I can't confirm 100% if your issue is fixed in those releases, as I am not completely sure if it was the same root issue. I wasn't able to reproduce an issue with the order of OneSignal methods you were calling.
However PR #2046 fixed a scenario where updates could stop applying in some cases when login was called. It's very possible some Users got stuck in a bad state if you ever changed the order of your OneSignal calls, or some older bug we didn't consider. The PR #2046 includes commit bc917772972ae5e652567d1fcb904d9516e40aff which specifically helps get Users out of one known bad state, so this may have been the key for you.

@softsan let me know if you continue to have this problem and I can reopen this issue.

**Comment by softsan** [comment]
@jkasten2 hi again! I have one user who is still having issue getting subscribed for OneSignal. He tried login with different user on the same device but no luck. He also tried his user on another device but it didn't work either. Also he cleared cache and data, logout and uninstalled the app and fresh install. He tried it on cellular, his comp wifi and also his home wifi but still i do not see any records of him in OneSignal subscription list. So any idea why he is the only one who has such problem?

**Comment by jkasten2** [comment]
@softsan thanks for reporting back! Just to confirm, so 5.1.8 and 5.1.9 fixed this issue for most users? However there is a case where one user is still stuck?

For this User, can they confirm they can access https://onesignal.com/ to ensure something on their device isn't blocking a connection to it. (I know we confirmed this before with other users, just not sure if you confirm it with this specific user)

Other than getting a logcat with VERBOSE logging (which would be a big ask for an end-user) I don't currently have any other ideas to debug the issue for a single user.

**Comment by softsan** [comment]
@jkasten2 Yes version 5.1.8 and 5.1.9 solved all user's issue except this one. I asked to open that url on user device mobile browser and it opens fine.

**Comment by softsan** [comment]
@jkasten2 Further on this, i created an in-app push prompt and it does receive on that user's device but still his device is not in the subscription list.

**Comment by jkasten2** [comment]
@softsan That is a good detail to know, this means that a OneSignal User and Subscription was created for the device. This means there is a OneSignalId and a OneSignal SubscriptionId you could capture from the device. You could send these values to your own server to get them and check the subscription status on the OneSignal dashboard.

**Comment by softsan** [comment]
@jkasten2 Yeah i already logs those info in my server and i see "_oneSignalId_" as **blank ("").** ExternalId is what my userId is but "oneSignalId" is always blank for this user. Also when i searched with the ExternalId in OneSignal Dashboard, it only shows subscription for Web only(as we also use OneSignal for Web). No Mobile device is listed in that.

**Comment by softsan** [comment]
@jkasten2 Further on this, now i can see user's device in subscription list but it says "Permission not granted". However I double checked and confirmed that he has provide push notification permissions.  Please help.


<img width="1025" alt="Screenshot 2024-05-14 at 7 54 06 PM" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/7391319/d0d97239-25ba-42be-a4da-681f943e811d">

When i open that subscription, there is no "Externalid" and i am pretty sure  I use that in my code:
<img width="468" alt="Screenshot 2024-05-14 at 7 54 42 PM" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/7391319/ee1eda62-e300-4764-8484-afae616ab84a">

**Comment by thepraveshsinghh** [comment]
One of our user is facing the same issue, playerId is blank.

 User is having Samsung S24Ultra.
 
 Tried upgrading OneSignal dependency version as told in the comments above but didn't help.
 
 Please suggest a solution.
